# Generated by Django 4.0.10 on 2023-06-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_city_alter_room_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='things_to_know',
            field=models.TextField(blank=True, null=True),
        ),
    ]
