# Generated by Django 4.0.10 on 2023-06-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userNotifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
