# Generated by Django 4.0.10 on 2023-06-27 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_fee', models.PositiveIntegerField(default=0)),
                ('room_fee', models.PositiveIntegerField(default=0)),
                ('cleaning_fee', models.PositiveIntegerField(default=0)),
                ('experience_fee', models.PositiveIntegerField(default=0)),
                ('tax', models.PositiveIntegerField(default=0)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingHistory', to='bookings.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
