# Generated by Django 4.0.10 on 2023-06-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingHistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='final_total_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
