# Generated by Django 4.0.10 on 2023-09-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_answer_details_alter_feedback_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='kind',
            field=models.CharField(max_length=50),
        ),
    ]
