# Generated by Django 4.0.10 on 2023-06-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('detail', models.CharField(default='', max_length=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
