# Generated by Django 4.0.10 on 2023-06-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsOption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsoption',
            name='detail',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
