# Generated by Django 4.0.10 on 2023-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.CharField(default='Calgary', max_length=80),
        ),
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.CharField(default='Cananda', max_length=50),
        ),
    ]
