# Generated by Django 4.0.10 on 2023-06-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_alter_experience_city_alter_experience_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='total_available_guest',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
