# Generated by Django 4.0.10 on 2023-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_accuracy_rating_review_check_in_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cleanliness_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='experience_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
