# Generated by Django 4.0.10 on 2023-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_city_alter_room_country'),
        ('experiences', '0002_alter_experience_city_alter_experience_country'),
        ('wishlists', '0002_remove_wishlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='experiences',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlists', to='experiences.experience'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlists', to='rooms.room'),
        ),
    ]
